name: uccelli_info_app
description: "Welcome to the Uccelli Society"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  html: ^0.15.1
  flutter_html: ^3.0.0-alpha.5
  url_launcher: ^6.3.1
  web: ^1.1.1
  provider: ^6.1.1
  shared_preferences: ^2.5.3
  google_maps_flutter: ^2.2.2
  geocoding: ^3.0.0
  animate_do: ^4.2.0
  share_plus: ^10.1.4
  package_info_plus: ^8.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # For generating launcher icons
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/logo_light.png"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/Logo_Uccelli_Quer_Negativ.png
    - lib/assets/images/Logo_Uccelli_Quer_Positiv.png
    - lib/assets/images/logo_light.png
    - lib/assets/images/logo_dark.png
