// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxQ0_GxyNyybdxnji9qFUwNnDxXLdW3ek',
    appId: '1:433095776698:web:7bdd47d1eb1e5a87cd6583',
    messagingSenderId: '433095776698',
    projectId: 'uccelli-infoapp-android',
    authDomain: 'uccelli-infoapp-android.firebaseapp.com',
    storageBucket: 'uccelli-infoapp-android.firebasestorage.app',
    measurementId: 'G-7YV3WQTXYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRh8IqXwLFCL2ZIQcMGP942vVijj3kexI',
    appId: '1:433095776698:android:1798f58e33526134cd6583',
    messagingSenderId: '433095776698',
    projectId: 'uccelli-infoapp-android',
    storageBucket: 'uccelli-infoapp-android.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_D2BtTk8P2WCpyAe_hAHXg0TucKeGhaM',
    appId: '1:433095776698:ios:d8b9e4bf42c164f7cd6583',
    messagingSenderId: '433095776698',
    projectId: 'uccelli-infoapp-android',
    storageBucket: 'uccelli-infoapp-android.firebasestorage.app',
    iosBundleId: 'com.example.uccelliInfoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_D2BtTk8P2WCpyAe_hAHXg0TucKeGhaM',
    appId: '1:433095776698:ios:d8b9e4bf42c164f7cd6583',
    messagingSenderId: '433095776698',
    projectId: 'uccelli-infoapp-android',
    storageBucket: 'uccelli-infoapp-android.firebasestorage.app',
    iosBundleId: 'com.example.uccelliInfoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxQ0_GxyNyybdxnji9qFUwNnDxXLdW3ek',
    appId: '1:433095776698:web:c5fe207aeff9fbafcd6583',
    messagingSenderId: '433095776698',
    projectId: 'uccelli-infoapp-android',
    authDomain: 'uccelli-infoapp-android.firebaseapp.com',
    storageBucket: 'uccelli-infoapp-android.firebasestorage.app',
    measurementId: 'G-GK01VTCSCL',
  );
}
