name: '📦 Build & Release APK'

on:
  push:
    tags:
      - 'v*'            # anything like v1.2.3
  workflow_dispatch:    # allow manual runs too

permissions:
  contents: write       # needed to create releases & upload assets

env:
  REPO: ${{ github.repository }}    # owner/repo
  TAG:  ${{ github.ref_name }}      # e.g. "v1.2.3"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    env:
      JKS_BASE64:         ${{ secrets.JKS_BASE64 }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_PASSWORD:      ${{ secrets.KEY_PASSWORD }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter (stable channel)
        uses: subosito/flutter-action@v1
        with:
          channel: stable
          # cache: true # NEU: Caching für Flutter SDK und pub-cache WIRD JETZT DEAKTIVIERT, um Inkonsistenzen zu vermeiden
          # Da das Problem so hartnäckig ist, erzwingen wir einen frischen Start bei jedem Run.
          # Diese Zeile wurde auskommentiert/entfernt.


      - name: Add Android SDK cmdline-tools to PATH # Fix für sdkmanager not found
        run: echo "PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

      # >>> Keystore-Pfad KORRIGIERT auf uccelli_info_app <<<
      - name: Decode & install keystore
        run: |
          mkdir -p uccelli_info_app/android/app # Verzeichnis im Projekt erstellen (relativ zum Repo-Root)
          echo "$JKS_BASE64" | base64 --decode \
            > uccelli_info_app/android/app/uccelli-release.jks # Keystore im Projekt ablegen (relativ zum Repo-Root)
      # >>> Ende Korrektur Keystore-Pfad <<<

      # >>> working-directory KORRIGIERT auf uccelli_info_app <<<
      - name: Accept Android SDK licenses
        working-directory: uccelli_info_app # In das Projektverzeichnis wechseln (damit sdkmanager in der richtigen Umgebung läuft, falls nötig)
        run: |
          yes | sdkmanager --install "platform-tools" "platforms;android-33" "cmdline-tools;latest"
          yes | sdkmanager --licenses
      # >>> Ende working-directory <<<

      # NEU HINZUGEFÜGT: Robuste Schritte für Abhängigkeiten und Lokalisierung
      - name: Clean Flutter project
        working-directory: uccelli_info_app
        run: flutter clean

      - name: Clear Flutter pub cache # NEU: Expliziter Schritt zum Bereinigen des pub-caches
        working-directory: uccelli_info_app
        run: flutter pub cache clean --force # Erzwingt die Bereinigung des gesamten Caches

      - name: Get Flutter dependencies (verbose)
        working-directory: uccelli_info_app
        run: flutter pub get --verbose

      - name: Generate localization files (verbose)
        working-directory: uccelli_info_app
        run: flutter gen-l10n --verbose
      # ENDE NEU HINZUGEFÜGT

      # >>> working-directory KORRIGIERT auf uccelli_info_app <<<
      - name: Build release APK
        working-directory: uccelli_info_app
        run: flutter build apk --release
      # >>> Ende working-directory <<<

      # >>> working-directory KORRIGIERT auf uccelli_info_app (für Zugriff auf build Output) <<<
      - name: Create GitHub Release via REST API
        id: create_release
        working-directory: uccelli_info_app
        run: |
          response=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/$REPO/releases \
            -d "{\"tag_name\":\"$TAG\",\"name\":\"Release $TAG\",\"draft\":false,\"prerelease\":false}")
          echo "$response"
          upload_url=$(echo "$response" | jq -r .upload_url | sed -e "s/{.*}//")
          echo "UPLOAD_URL=$upload_url" >> $GITHUB_ENV
      # >>> Ende working-directory <<<

      # >>> working-directory KORRIGIERT auf uccelli_info_app (für Zugriff auf build Output) <<<
      - name: Upload APK asset via REST API
        working-directory: uccelli_info_app
        run: |
          curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/vnd.android.package-archive" \
            --data-binary @build/app/outputs/flutter-apk/app-release.apk \
            "${UPLOAD_URL}?name=uccelli-info-app-${TAG}.apk"
      # >>> Ende working-directory <<<
