// lib/main.dart

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

// Hive for local cache
import 'package:hive_flutter/hive_flutter.dart';
import 'services/post_cache_service.dart';

// Push-notification setup
import 'services/push_notification_service.dart';

// State providers
import 'providers/theme_provider.dart';
import 'providers/favorites_provider.dart';

// Entry page
import 'pages/splash_screen.dart';

// >>> Korrigierter Import für generierten Lokalisierungs-Code <<<
import 'package:uccelli_info_app/gen_l10n/app_localizations.dart'; // <<< HIER IST DIE KRITISCHE ÄNDERUNG
// >>> Importiere Standard Lokalisierungs-Delegates <<<
import 'package:flutter_localizations/flutter_localizations.dart';

// NEU: Supabase Import
import 'package:supabase_flutter/supabase_flutter.dart';


Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // 1️⃣ Initialize Supabase Client
  await Supabase.initialize(
    url: 'https://sgauimtpyxqikwuppahe.supabase.co',
    anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnYXVpbXRweXhxaWt3dXBwYWhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMjA4NzksImV4cCI6MjA2NDU5Njg3OX0.6kGegXvsNNJalkCU7p2VgLsd-3cMd_clFMkaFlE3wwM',
    debug: true,
  );

  // 2️⃣ Initialize Hive and open your cache box
  await Hive.initFlutter();
  await Hive.openBox(PostCacheService.postsBoxName);

  // 3️⃣ Initialize local notifications (Firebase Messaging-bezogene Teile wurden bereits entfernt)
  await PushNotificationService.init();

  // 4️⃣ Launch the app
  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => ThemeProvider()),
        ChangeNotifierProvider(create: (_) => FavoritesProvider()),
      ],
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  static _MyAppState? of(BuildContext context) =>
      context.findAncestorStateOfType<_MyAppState>();


  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  Locale? _locale;

  @override
  void initState() {
    super.initState();
    _loadLocalePreference();
  }

  Future<void> _loadLocalePreference() async {
    final prefs = await SharedPreferences.getInstance();
    final savedLangCode = prefs.getString('user_language_code');

    if (savedLangCode != null) {
      final loadedLocale = Locale(savedLangCode);
      if (AppLocalizations.supportedLocales.contains(loadedLocale)) {
        setState(() {
          _locale = loadedLocale;
        });
      } else {
        setState(() {
          _locale = null;
        });
      }
    }
  }

  void setLocale(Locale locale) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('user_language_code', locale.languageCode);
    setState(() {
      _locale = locale;
    });
  }


  @override
  Widget build(BuildContext context) {
    final themeProv = Provider.of<ThemeProvider>(context);

    const primary   = Color(0xFFDFBF8F);
    const greyAcc   = Color(0xFF6A6A6A);
    const darkBg    = Color(0xFF252525);

    final light = ThemeData(
      brightness: Brightness.light,
      primaryColor: primary,
      scaffoldBackgroundColor: Colors.white,
      cardColor: Colors.white,
      appBarTheme: const AppBarTheme(
        backgroundColor: primary,
        foregroundColor: Colors.white,
      ),
      inputDecorationTheme: InputDecorationTheme(
        filled: true,
        fillColor: Colors.white,
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
          borderSide: BorderSide(color: greyAcc),
        ),
      ),
      colorScheme: ColorScheme.fromSwatch(accentColor: greyAcc),
    );

    final dark = ThemeData(
      brightness: Brightness.dark,
      primaryColor: primary,
      scaffoldBackgroundColor: darkBg,
      cardColor: darkBg,
      appBarTheme: const AppBarTheme(
        backgroundColor: darkBg,
        foregroundColor: Colors.white,
      ),
      inputDecorationTheme: InputDecorationTheme(
        filled: true,
        fillColor: darkBg.withOpacity(0.2),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
          borderSide: BorderSide(color: greyAcc),
        ),
      ),
      colorScheme: ColorScheme.fromSwatch(
        brightness: Brightness.dark,
        accentColor: greyAcc,
      ),
    );

    return MaterialApp(
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: AppLocalizations.supportedLocales,
      locale: _locale,

      title: 'Uccelli Society',
      debugShowCheckedModeBanner: false,
      themeMode: themeProv.themeMode,
      theme: light,
      darkTheme: dark,
      home: const SplashScreen(),
    );
  }
}
