name: Flutter CI - Android Release

on:
  # Erlaubt das manuelle Starten des Workflows über den "Actions" Tab
  workflow_dispatch:

  # Löst den Workflow automatisch aus, wenn ein neuer Tag (z.B. v1.0.2) gepusht wird
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    # Setzt das Standard-Arbeitsverzeichnis für die meisten Schritte
    defaults:
      run:
        working-directory: ./uccelli_info_app

    steps:
      # 1. Code aus dem Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Java Development Kit (JDK) 17 einrichten
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Flutter SDK einrichten
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
          cache: true

      # 4. Ausführungsrechte für den Gradle Wrapper setzen
      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew
          
      # 5. Abhängigkeiten installieren und Lokalisierungsdateien generieren
      - name: Install dependencies and generate files
        run: |
          flutter pub get
          flutter gen-l10n

      # 6. Keystore aus GitHub Secret wiederherstellen
      - name: Decode Keystore
        working-directory: ./uccelli_info_app/android
        run: echo "${{ secrets.JKS_BASE64 }}" | base64 --decode > upload-keystore.jks

      # 7. App bauen und signieren
      - name: Build and Sign App
        working-directory: ./uccelli_info_app/android
        run: ./gradlew assembleRelease
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      # 8. Release-Artefakt umbenennen
      - name: Rename release artifact
        run: mv android/app/build/outputs/apk/release/app-release.apk android/app/build/outputs/apk/release/uccelli-app-${{ github.ref_name }}.apk

      # 9. GitHub Release erstellen und APK hochladen
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: uccelli_info_app/android/app/build/outputs/apk/release/uccelli-app-${{ github.ref_name }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
