name: '📦 Build & Release APK'

on:
  push:
    tags:
      - 'v*'             # anything like v1.2.3
  workflow_dispatch:    # allow manual runs too

permissions:
  contents: write       # needed to create releases & upload assets

env:
  REPO: ${{ github.repository }}     # owner/repo
  TAG:  ${{ github.ref_name }}       # e.g. "v1.2.3"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    env:
      JKS_BASE64:        ${{ secrets.JKS_BASE64 }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_PASSWORD:      ${{ secrets.KEY_PASSWORD }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter (stable channel)
        uses: subosito/flutter-action@v1
        with:
          channel: stable
          # Optional: Du könntest hier caching für das Flutter SDK aktivieren:
          # cache: true

      - name: Add Android SDK cmdline-tools to PATH # Fix für sdkmanager not found
        run: echo "PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

      # >>> Keystore-Pfad KORRIGIERT auf flutter/uccelli_info_app <<<
      - name: Decode & install keystore
        run: |
          mkdir -p flutter/uccelli_info_app/android/app # Verzeichnis im Projekt erstellen (relativ zum Repo-Root)
          echo "$JKS_BASE64" | base64 --decode \
            > flutter/uccelli_info_app/android/app/uccelli-release.jks # Keystore im Projekt ablegen (relativ zum Repo-Root)
      # >>> Ende Korrektur Keystore-Pfad <<<

      # >>> working-directory hinzugefügt <<<
      - name: Accept Android SDK licenses
        working-directory: flutter/uccelli_info_app # In das Projektverzeichnis wechseln (damit sdkmanager in der richtigen Umgebung läuft, falls nötig)
        run: |
          # Es ist möglich, dass dieser Schritt hier nicht nötig ist, wenn subosito/flutter-action ihn abdeckt.
          # Aber wenn der Fehler wieder auftritt, ist dies der richtige Ort dafür.
          yes | sdkmanager --install "platform-tools" "platforms;android-33" "cmdline-tools;latest"
          yes | sdkmanager --licenses
      # >>> Ende working-directory <<<


      # >>> working-directory KORRIGIERT auf flutter/uccelli_info_app <<<
      - name: Get Flutter dependencies
        working-directory: flutter/uccelli_info_app # In das Projektverzeichnis wechseln
        run: flutter pub get
      # >>> Ende working-directory <<<

      # >>> working-directory KORRIGIERT auf flutter/uccelli_info_app <<<
      - name: Build release APK
        working-directory: flutter/uccelli_info_app # In das Projektverzeichnis wechseln
        run: flutter build apk --release
      # >>> Ende working-directory <<<

      # >>> working-directory KORRIGIERT auf flutter/uccelli_info_app (für Zugriff auf build Output) <<<
      - name: Create GitHub Release via REST API
        id: create_release
        working-directory: flutter/uccelli_info_app # In das Projektverzeichnis wechseln
        run: |
          response=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/$REPO/releases \
            -d "{\"tag_name\":\"$TAG\",\"name\":\"Release $TAG\",\"draft\":false,\"prerelease\":false}")
          echo "$response"
          upload_url=$(echo "$response" | jq -r .upload_url | sed -e "s/{.*}//")
          echo "UPLOAD_URL=$upload_url" >> $GITHUB_ENV
      # >>> Ende working-directory <<<

      # >>> working-directory KORRIGIERT auf flutter/uccelli_info_app (für Zugriff auf build Output) <<<
      - name: Upload APK asset via REST API
        working-directory: flutter/uccelli_info_app # In das Projektverzeichnis wechseln
        run: |
          curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/vnd.android.package-archive" \
            --data-binary @build/app/outputs/flutter-apk/app-release.apk \
            "${UPLOAD_URL}?name=uccelli-info-app-${TAG}.apk"
      # >>> Ende working-directory <<<