# .github/workflows/build-release.yml
name: '📦 Build & Archive Release APK'

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest

    env:
      JKS_BASE64:        ${{ secrets.JKS_BASE64 }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_PASSWORD:      ${{ secrets.KEY_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Decode keystore
        run: echo "$JKS_BASE64" | base64 --decode > android/app/uccelli-release.jks

      - name: Accept SDK licenses
        run: |
          yes | sdkmanager --install "platform-tools" "platforms;android-33" "cmdline-tools;latest"
          yes | sdkmanager --licenses

      - run: flutter pub get

      - run: flutter build apk --release

      - uses: actions/upload-artifact@v3.1.2    # pin to a real v3 patch
        with:
          name: uccelli-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
