name: '📦 Build & Release APK'

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    env:
      JKS_BASE64:        ${{ secrets.JKS_BASE64 }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_PASSWORD:      ${{ secrets.KEY_PASSWORD }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Set up Flutter (stable channel)
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Decode & install keystore
        run: |
          mkdir -p android/app
          echo "$JKS_BASE64" | base64 --decode > android/app/uccelli-release.jks

      - name: Accept Android SDK licenses
        run: |
          # Try the new cmdline-tools path first
          if [ -x "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" ]; then
            yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" --licenses
          # Fallback to the legacy tools path
          elif [ -x "$ANDROID_SDK_ROOT/tools/bin/sdkmanager" ]; then
            yes | "$ANDROID_SDK_ROOT/tools/bin/sdkmanager" --licenses
          else
            echo "sdkmanager not found, skipping license acceptance"
          fi

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload APK to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: uccelli-info-app-${{ github.ref_name }}.apk
          asset_content_type: application/vnd.android.package-archive
