name: '📦 Build & Release APK'

on:
  push:
    tags:
      - 'v*'             # anything like v1.2.3
  workflow_dispatch:    # allow manual runs too

permissions:
  contents: write       # needed to create releases & upload assets

env:
  REPO: ${{ github.repository }}   # owner/repo
  TAG:  ${{ github.ref_name }}     # e.g. "v1.2.3"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    env:
      JKS_BASE64:        ${{ secrets.JKS_BASE64 }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_PASSWORD:      ${{ secrets.KEY_PASSWORD }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter (stable channel)
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Decode & install keystore
        run: |
          mkdir -p android/app
          echo "$JKS_BASE64" | base64 --decode \
            > android/app/uccelli-release.jks

      - name: Accept Android SDK licenses
        run: |
          yes | sdkmanager --install "platform-tools" "platforms;android-33" "cmdline-tools;latest"
          yes | sdkmanager --licenses

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: Create GitHub Release via REST API
        id: create_release
        run: |
          response=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/$REPO/releases \
            -d "{\"tag_name\":\"$TAG\",\"name\":\"Release $TAG\",\"draft\":false,\"prerelease\":false}")
          echo "$response"
          upload_url=$(echo "$response" | jq -r .upload_url | sed -e "s/{.*}//")
          echo "UPLOAD_URL=$upload_url" >> $GITHUB_ENV

      - name: Upload APK asset via REST API
        run: |
          curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/vnd.android.package-archive" \
            --data-binary @build/app/outputs/flutter-apk/app-release.apk \
            "${UPLOAD_URL}?name=uccelli-info-app-${TAG}.apk"
