name: Flutter CI - Android Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    # Standard-Verzeichnis f端r die meisten Schritte
    defaults:
      run:
        working-directory: ./uccelli_info_app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
          cache: true
          cache-key: flutter-${{ runner.os }}-${{ matrix.flutter-version }}-${{ hashFiles('**/pubspec.lock') }}

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew
          
      - name: Install dependencies and generate files
        run: |
          flutter pub get
          flutter gen-l10n

      # --- FINALE KORREKTUR HIER ---
      - name: Build Flutter App
        # Wir wechseln f端r diesen einen Schritt in das android-Verzeichnis
        working-directory: ./uccelli_info_app/android
        # Und f端hren den Befehl direkt dort aus
        run: ./gradlew assembleRelease

      - name: Rename release artifact
        # Dieser Schritt wird wieder im Standard-Verzeichnis ausgef端hrt
        run: mv android/app/build/outputs/apk/release/app-release.apk android/app/build/outputs/apk/release/uccelli-app-${{ github.ref_name }}.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          # Der Pfad vom Root aus bleibt gleich
          files: uccelli_info_app/android/app/build/outputs/apk/release/uccelli-app-${{ github.ref_name }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
