name: '📦 Build & Archive Release APK'

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest

    env:
      JKS_BASE64:        ${{ secrets.JKS_BASE64 }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_PASSWORD:      ${{ secrets.KEY_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Decode keystore
        run: |
          echo "$JKS_BASE64" | base64 --decode > android/app/uccelli-release.jks

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Release APK
        run: flutter build apk --release

      - name: Archive APK
        uses: actions/upload-artifact@v3     # <— use the v3 tag here
        with:
          name: uccelli-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
